### ISSUE TITLE
compile errors

### ISSUE THREAD

**Issue by ericgorr** [BestSolution-at/fixtar#2]
~/d/f/src (master) $ make
gcc -g3 -I. -Wall   -O2 -c ft.c
ft.c:41:5: error: expected parameter declarator
int snprintf(char _str, size_t size, const char *format, ...);
    ^
/usr/include/secure/_stdio.h:57:39: note: expanded from macro 'snprintf'
  __builtin___snprintf_chk (str, len, 0, __darwin_obsz(str), __VA_ARGS__)
                                      ^
ft.c:41:5: error: expected ')'
/usr/include/secure/_stdio.h:57:39: note: expanded from macro 'snprintf'
  __builtin___snprintf_chk (str, len, 0, __darwin_obsz(str), __VA_ARGS__)
                                      ^
ft.c:41:5: note: to match this '('
/usr/include/secure/_stdio.h:57:28: note: expanded from macro 'snprintf'
  __builtin___snprintf_chk (str, len, 0, __darwin_obsz(str), __VA_ARGS__)
                           ^
ft.c:41:5: error: conflicting types for '**builtin___snprintf_chk'
int snprintf(char *str, size_t size, const char *format, ...);
    ^
/usr/include/secure/_stdio.h:57:3: note: expanded from macro 'snprintf'
  __builtin___snprintf_chk (str, len, 0, __darwin_obsz(str), __VA_ARGS**)
  ^
ft.c:41:5: note: '**builtin___snprintf_chk' is a builtin with type 'int (char *,
      unsigned long, int, unsigned long, const char *, ...)'
/usr/include/secure/_stdio.h:57:3: note: expanded from macro 'snprintf'
  __builtin___snprintf_chk (str, len, 0, __darwin_obsz(str), __VA_ARGS**)
  ^
3 errors generated.
make: *_\* [ft.o] Error 1

**Comment by daudo** [comment]
this is a OS/X only issue, correction will follow shortly
